<center>
<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-RP0101EN-Coursera/v2/M5_Final/images/SN_web_lightmode.png" width="300">
</center>

<h1>Analysis of Global COVID-19 Pandemic Data</h1>

Estimated time needed: **90** minutes

## Overview:

In this final project, you will apply your knowledge of data analysis by completing a series of hands-on tasks in this lab notebook. The lab consists of 10 tasks, where you will write and execute code to demonstrate your skills.

While working through the lab, remember to save all your code and outputs, then download the Jupyter Notebook, as you will need to submit the completed notebook for the **Final Project: Submission and Evaluation**.

If you need to refresh your memories about specific coding details, you may refer to previous hands-on labs for code examples.

In [ ]:
# This lab requires 'httr' and 'rvest'packages, which are already pre-loaded into this lab environment.
# However, if you are working on your local RStudio, please uncomment the below codes and install the packages.

#install.packages("httr")
#install.packages("rvest")

In [1]:
library(httr)
library(rvest)

Note: if you can import above libraries, please use install.packages() to install them first.

## TASK 1: Get a `COVID-19 pandemic` Wiki page using HTTP request

First, let's write a function to use HTTP request to get a public COVID-19 Wiki page.

Before you write the function, you can open this public page from this 

URL https://en.wikipedia.org/w/index.php?title=Template:COVID-19_testing_by_country using a web browser.

The goal of task 1 is to get the html page using HTTP request (`httr` library)

In [2]:

get_wiki_covid19_page <- function() {
    
  # Our target COVID-19 wiki page URL is: https://en.wikipedia.org/w/index.php?title=Template:COVID-19_testing_by_country  
  # Which has two parts: 
    # 1) base URL `https://en.wikipedia.org/w/index.php  
    # 2) URL parameter: `title=Template:COVID-19_testing_by_country`, seperated by question mark ?
    
  # Wiki page base
  wiki_base_url <- "https://en.wikipedia.org/w/index.php"
  # You will need to create a List which has an element called `title` to specify which page you want to get from Wiki
  # in our case, it will be `Template:COVID-19_testing_by_country`
  query_params <- list(title = "Template:COVID-19_testing_by_country")
    
  # - Use the `GET` function in httr library with a `url` argument and a `query` arugment to get a HTTP response
  response <- GET(url = wiki_base_url, query = query_params)
  # Use the `return` function to return the response
  return(response)
}

Call the `get_wiki_covid19_page` function to get a http response with the target html page

In [3]:
# Call the get_wiki_covid19_page function and print the response
response <- get_wiki_covid19_page()

# Print the response
print(response)

Response [https://en.wikipedia.org/w/index.php?title=Template%3ACOVID-19_testing_by_country]
  Date: 2026-06-13 14:47
  Status: 200
  Content-Type: text/html; charset=UTF-8
  Size: 458 kB
<!DOCTYPE html>
<html class="client-nojs vector-feature-language-in-header-enabled vector-fea...
<head>
<meta charset="UTF-8">
<title>Template:COVID-19 testing by country - Wikipedia</title>
<script>(function(){var className="client-js vector-feature-language-in-heade...
RLSTATE={"ext.globalCssJs.user.styles":"ready","site.styles":"ready","user.st...
<script>(RLQ=window.RLQ||[]).push(function(){mw.loader.impl(function(){return...
}];});});</script>
<link rel="stylesheet" href="/w/load.php?lang=en&amp;modules=ext.cite.styles%...
...

## TASK 2: Extract COVID-19 testing data table from the wiki HTML page

On the COVID-19 testing wiki page, you should see a data table `<table>` node contains COVID-19 testing data by country on the page:

<a href="https://cognitiveclass.ai/">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-RP0101EN-Coursera/v2/M5_Final/images/covid-19-by-country.png" width="400" align="center">
</a>

Note the numbers you actually see on your page may be different from above because it is still an on-going pandemic when creating this notebook.

The goal of task 2 is to extract above data table and convert it into a data frame

Now use the `read_html` function in rvest library to get the root html node from response

In [4]:
# Get the root html node from the http response in task 1 
root_node <- read_html(response)
root_node

{html_document}
<html class="client-nojs vector-feature-language-in-header-enabled vector-feature-language-in-main-menu-disabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-sticky-header-enabled vector-toc-available skin-thumbsize-clientpref-standard" lang="en" dir="ltr">
[1] <head>\n<meta http-equiv="Content-Type" content="text/html; charset=UTF-8 ...
[2] <body class="skin--responsive skin-vector skin-vector-search-vue mediawik ...

Get the tables in the HTML root node using `html_nodes` function.

In [11]:
# Get the table node from the root html node
all_table_node <- html_nodes(root_node, "table")
all_table_node

{xml_nodeset (4)}
[1] <table class="box-Update plainlinks ombox ombox-content ambox-Update" rol ...
[2] <table class="wikitable plainrowheaders sortable collapsible autocollapse ...
[3] <table class="plainlinks ombox mbox-small ombox-notice" role="presentatio ...
[4] <table class="wikitable mw-templatedata-doc-params">\n<caption><p class=" ...

Read the specific table from the multiple tables in the `table_node` using the `html_table` function and convert it into dataframe using `as.data.frame`

_Hint:- Please read the `table_node` with index 2(ex:- table_node[2])._

In [39]:
# Read the table node and convert it into a data frame, and print the data frame for review
table_node <- all_table_node[2]
data_frame <- html_table(table_node)
print(data_frame)

[[1]]
# A tibble: 173 × 9
   `Country or region` `Date[a]`   Tested      `Units[b]` `Confirmed(cases)`
   <chr>               <chr>       <chr>       <chr>      <chr>
 1 Afghanistan         17 Dec 2020 154,767     samples    49,621
 2 Albania             18 Feb 2021 428,654     samples    96,838
 3 Algeria             2 Nov 2020  230,553     samples    58,574
 4 Andorra             23 Feb 2022 300,307     samples    37,958
 5 Angola              2 Feb 2021  399,228     samples    20,981
 6 Antigua and Barbuda 6 Mar 2021  15,268      samples    832
 7 Argentina           16 Apr 2022 35,716,069  samples    9,060,495
 8 Armenia             29 May 2022 3,099,602   samples    422,963
 9 Australia           9 Sep 2022  78,548,492  samples    10,112,229
10 Austria             1 Feb 2023  205,817,752 samples    5,789,991
# ℹ 163 more rows
# ℹ 4 more variables: `Confirmed /tested,%` <chr>,
#   `Tested /population,%` <chr>, `Confirmed /population,%` <chr>, Ref. <chr>

## TASK 3: Pre-process and export the extracted data frame

The goal of task 3 is to pre-process the extracted data frame from the previous step, and export it as a csv file

Let's get a summary of the data frame

In [40]:
# Print the summary of the data frame
data_frame <- data_frame[[1]]
summary(data_frame)
str(data_frame)

class(data_frame)

head(data_frame)

 Country or region    Date[a]             Tested            Units[b]
 Length:173         Length:173         Length:173         Length:173
 Class :character   Class :character   Class :character   Class :character
 Mode  :character   Mode  :character   Mode  :character   Mode  :character
 Confirmed(cases)   Confirmed /tested,% Tested /population,%
 Length:173         Length:173          Length:173
 Class :character   Class :character    Class :character
 Mode  :character   Mode  :character    Mode  :character
 Confirmed /population,%     Ref.
 Length:173              Length:173
 Class :character        Class :character
 Mode  :character        Mode  :character

tibble [173 × 9] (S3: tbl_df/tbl/data.frame)
 $ Country or region      : chr [1:173] "Afghanistan" "Albania" "Algeria" "Andorra" ...
 $ Date[a]                : chr [1:173] "17 Dec 2020" "18 Feb 2021" "2 Nov 2020" "23 Feb 2022" ...
 $ Tested                 : chr [1:173] "154,767" "428,654" "230,553" "300,307" ...
 $ Units[b]               : chr [1:173] "samples" "samples" "samples" "samples" ...
 $ Confirmed(cases)       : chr [1:173] "49,621" "96,838" "58,574" "37,958" ...
 $ Confirmed /tested,%    : chr [1:173] "32.1" "22.6" "25.4" "12.6" ...
 $ Tested /population,%   : chr [1:173] "0.40" "15.0" "0.53" "387" ...
 $ Confirmed /population,%: chr [1:173] "0.13" "3.4" "0.13" "49.0" ...
 $ Ref.                   : chr [1:173] "[1]" "[2]" "[3][4]" "[5]" ...

[1] "tbl_df"     "tbl"        "data.frame"

  Country or region   Date[a]     Tested  Units[b] Confirmed(cases)
1 Afghanistan         17 Dec 2020 154,767 samples  49,621
2 Albania             18 Feb 2021 428,654 samples  96,838
3 Algeria             2 Nov 2020  230,553 samples  58,574
4 Andorra             23 Feb 2022 300,307 samples  37,958
5 Angola              2 Feb 2021  399,228 samples  20,981
6 Antigua and Barbuda 6 Mar 2021  15,268  samples  832
  Confirmed /tested,% Tested /population,% Confirmed /population,% Ref.
1 32.1                0.40                 0.13                    [1]
2 22.6                15.0                 3.4                     [2]
3 25.4                0.53                 0.13                    [3][4]
4 12.6                387                  49.0                    [5]
5 5.3                 1.3                  0.067                   [6]
6 5.4                 15.9                 0.86                    [7]

As you can see from the summary, the columns names are little bit different to understand and some column data types are not correct. For example, the `Tested` column shows as `character`. 

As such, the data frame read from HTML table will need some pre-processing such as removing irrelvant columns, renaming columns, and convert columns into proper data types.

We have prepared a pre-processing function for you to conver the data frame but you can also try to write one by yourself

In [45]:
preprocess_covid_data_frame <- function(data_frame) {
    
    shape <- dim(data_frame)

    # Remove the World row
    data_frame<-data_frame[!(data_frame$`Country or region`=="World"),]
    # Remove the last row
    data_frame <- data_frame[1:172, ]
    
    # We dont need the Units and Ref columns, so can be removed
    data_frame["Ref."] <- NULL
    data_frame["Units[b]"] <- NULL
    
    # Renaming the columns
    names(data_frame) <- c("country", "date", "tested", "confirmed", "confirmed.tested.ratio", "tested.population.ratio", "confirmed.population.ratio")
    
    # Convert column data types
    data_frame$country <- as.factor(data_frame$country)
    data_frame$date <- as.factor(data_frame$date)
    data_frame$tested <- as.numeric(gsub(",","",data_frame$tested))
    data_frame$confirmed <- as.numeric(gsub(",","",data_frame$confirmed))
    data_frame$'confirmed.tested.ratio' <- as.numeric(gsub(",","",data_frame$`confirmed.tested.ratio`))
    data_frame$'tested.population.ratio' <- as.numeric(gsub(",","",data_frame$`tested.population.ratio`))
    data_frame$'confirmed.population.ratio' <- as.numeric(gsub(",","",data_frame$`confirmed.population.ratio`))
    
    return(data_frame)
}

Call the `preprocess_covid_data_frame` function

In [46]:
# call `preprocess_covid_data_frame` function and assign it to a new data frame
cleaned_covid_data <- preprocess_covid_data_frame(data_frame)

# View the result
head(cleaned_covid_data)
summary(cleaned_covid_data)

  country             date        tested confirmed confirmed.tested.ratio
1 Afghanistan         17 Dec 2020 154767 49621     32.1
2 Albania             18 Feb 2021 428654 96838     22.6
3 Algeria             2 Nov 2020  230553 58574     25.4
4 Andorra             23 Feb 2022 300307 37958     12.6
5 Angola              2 Feb 2021  399228 20981      5.3
6 Antigua and Barbuda 6 Mar 2021   15268   832      5.4
  tested.population.ratio confirmed.population.ratio
1   0.40                   0.130
2  15.00                   3.400
3   0.53                   0.130
4 387.00                  49.000
5   1.30                   0.067
6  15.90                   0.860

                country             date         tested
 Afghanistan        :  1   2 Feb 2023 :  6   Min.   :     3880
 Albania            :  1   1 Feb 2023 :  4   1st Qu.:   512037
 Algeria            :  1   31 Jan 2023:  4   Median :  3029859
 Andorra            :  1   1 Mar 2021 :  3   Mean   : 31377219
 Angola             :  1   23 Jul 2021:  3   3rd Qu.: 12386725
 Antigua and Barbuda:  1   29 Jan 2023:  3   Max.   :929349291
 (Other)            :166   (Other)    :149
   confirmed        confirmed.tested.ratio tested.population.ratio
 Min.   :       0   Min.   : 0.00          Min.   :   0.006
 1st Qu.:   37839   1st Qu.: 5.00          1st Qu.:   9.475
 Median :  281196   Median :10.05          Median :  46.950
 Mean   : 2508340   Mean   :11.25          Mean   : 175.504
 3rd Qu.: 1278105   3rd Qu.:15.25          3rd Qu.: 156.500
 Max.   :90749469   Max.   :46.80          Max.   :3223.000

 confirmed.population.ratio
 Min.   : 0.000
 1st Qu.: 0.425
 Median : 6.100
 Mean   :12.769
 3rd Qu.:16.250
 Max.   :74.400

Get the summary of the processed data frame again

In [47]:
# Print the summary of the processed data frame again
summary(cleaned_covid_data)

# Structure of the processed data
str(cleaned_covid_data)

# First few rows
head(cleaned_covid_data)

                country             date         tested
 Afghanistan        :  1   2 Feb 2023 :  6   Min.   :     3880
 Albania            :  1   1 Feb 2023 :  4   1st Qu.:   512037
 Algeria            :  1   31 Jan 2023:  4   Median :  3029859
 Andorra            :  1   1 Mar 2021 :  3   Mean   : 31377219
 Angola             :  1   23 Jul 2021:  3   3rd Qu.: 12386725
 Antigua and Barbuda:  1   29 Jan 2023:  3   Max.   :929349291
 (Other)            :166   (Other)    :149
   confirmed        confirmed.tested.ratio tested.population.ratio
 Min.   :       0   Min.   : 0.00          Min.   :   0.006
 1st Qu.:   37839   1st Qu.: 5.00          1st Qu.:   9.475
 Median :  281196   Median :10.05          Median :  46.950
 Mean   : 2508340   Mean   :11.25          Mean   : 175.504
 3rd Qu.: 1278105   3rd Qu.:15.25          3rd Qu.: 156.500
 Max.   :90749469   Max.   :46.80          Max.   :3223.000

 confirmed.population.ratio
 Min.   : 0.000
 1st Qu.: 0.425
 Median : 6.100
 Mean   :12.769
 3rd Qu.:16.250
 Max.   :74.400

tibble [172 × 7] (S3: tbl_df/tbl/data.frame)
 $ country                   : Factor w/ 172 levels "Afghanistan",..: 1 2 3 4 5 6 7 8 9 10 ...
 $ date                      : Factor w/ 141 levels "1 Aug 2021","1 Feb 2023",..: 32 38 49 60 44 124 29 90 141 2 ...
 $ tested                    : num [1:172] 154767 428654 230553 300307 399228 ...
 $ confirmed                 : num [1:172] 49621 96838 58574 37958 20981 ...
 $ confirmed.tested.ratio    : num [1:172] 32.1 22.6 25.4 12.6 5.3 5.4 25.4 13.6 12.9 2.8 ...
 $ tested.population.ratio   : num [1:172] 0.4 15 0.53 387 1.3 ...
 $ confirmed.population.ratio: num [1:172] 0.13 3.4 0.13 49 0.067 0.86 20 14.3 40.3 65 ...

  country             date        tested confirmed confirmed.tested.ratio
1 Afghanistan         17 Dec 2020 154767 49621     32.1
2 Albania             18 Feb 2021 428654 96838     22.6
3 Algeria             2 Nov 2020  230553 58574     25.4
4 Andorra             23 Feb 2022 300307 37958     12.6
5 Angola              2 Feb 2021  399228 20981      5.3
6 Antigua and Barbuda 6 Mar 2021   15268   832      5.4
  tested.population.ratio confirmed.population.ratio
1   0.40                   0.130
2  15.00                   3.400
3   0.53                   0.130
4 387.00                  49.000
5   1.30                   0.067
6  15.90                   0.860

After pre-processing, you can see the columns and columns names are simplified, and columns types are converted into correct types.

The data frame has following columns:

- **country** - The name of the country
- **date** - Reported date
- **tested** - Total tested cases by the reported date
- **confirmed** - Total confirmed cases by the reported date
- **confirmed.tested.ratio** - The ratio of confirmed cases to the tested cases
- **tested.population.ratio** - The ratio of tested cases to the population of the country
- **confirmed.population.ratio** - The ratio of confirmed cases to the population of the country

OK, we can call `write.csv()` function to save the csv file into a file.

In [48]:
# Export the data frame to a csv file
write.csv(cleaned_covid_data, "covid19_cleaned_data.csv", row.names = FALSE)

# Confirm the file was created
list.files(pattern = "covid19_cleaned_data.csv")

[1] "covid19_cleaned_data.csv"

Note for IBM Waston Studio, there is no traditional "hard disk" associated with a R workspace.

Even if you call `write.csv()` method to save the data frame as a csv file, it won't be shown in IBM Cloud Object Storage asset UI automatically.

However, you may still check if the `covid.csv` exists using following code snippet:

In [50]:
# Get working directory
wd <- getwd()
# Get exported 
file_path <- paste(wd, sep="", "/covid19_cleaned_data.csv")
# File path
print(file_path)
file.exists(file_path)

[1] "/resources/RP0101EN/labs/M5/covid19_cleaned_data.csv"

[1] TRUE

**Optional Step**: If you have difficulties finishing above webscraping tasks, you may still continue with next tasks by downloading a provided csv file from here:

In [ ]:
## Download a sample csv file
# covid_csv_file <- download.file("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-RP0101EN-Coursera/v2/dataset/covid.csv", destfile="covid.csv")
# covid_data_frame_csv <- read.csv("covid.csv", header=TRUE, sep=",")

## TASK 4: Get a subset of the extracted data frame

The goal of task 4 is to get the 5th to 10th rows from the data frame with only `country` and `confirmed` columns selected

In [53]:
# Read covid_data_frame_csv from the csv file
covid_data_frame_csv <- read.csv("covid19_cleaned_data.csv")
head(covid_data_frame_csv)
summary(covid_data_frame_csv)
# Get the 5th to 10th rows, with "country" and "confirmed" columns
result <- covid_data_frame_csv[5:10, c("country", "confirmed")]

# View the result
print(result)

  country             date        tested confirmed confirmed.tested.ratio
1 Afghanistan         17 Dec 2020 154767 49621     32.1
2 Albania             18 Feb 2021 428654 96838     22.6
3 Algeria             2 Nov 2020  230553 58574     25.4
4 Andorra             23 Feb 2022 300307 37958     12.6
5 Angola              2 Feb 2021  399228 20981      5.3
6 Antigua and Barbuda 6 Mar 2021   15268   832      5.4
  tested.population.ratio confirmed.population.ratio
1   0.40                   0.130
2  15.00                   3.400
3   0.53                   0.130
4 387.00                  49.000
5   1.30                   0.067
6  15.90                   0.860

   country              date               tested            confirmed
 Length:172         Length:172         Min.   :     3880   Min.   :       0
 Class :character   Class :character   1st Qu.:   512037   1st Qu.:   37839
 Mode  :character   Mode  :character   Median :  3029859   Median :  281196
                                       Mean   : 31377219   Mean   : 2508340
                                       3rd Qu.: 12386725   3rd Qu.: 1278105
                                       Max.   :929349291   Max.   :90749469
 confirmed.tested.ratio tested.population.ratio confirmed.population.ratio
 Min.   : 0.00          Min.   :   0.006        Min.   : 0.000
 1st Qu.: 5.00          1st Qu.:   9.475        1st Qu.: 0.425
 Median :10.05          Median :  46.950        Median : 6.100
 Mean   :11.25          Mean   : 175.504        Mean   :12.769
 3rd Qu.:15.25          3rd Qu.: 156.500        3rd Qu.:16.250
 Max.   :46.80          Max.   :3223.000        Max.   :74.400

               country confirmed
5               Angola     20981
6  Antigua and Barbuda       832
7            Argentina   9060495
8              Armenia    422963
9            Australia  10112229
10             Austria   5789991

## TASK 5: Calculate worldwide COVID testing positive ratio

The goal of task 5 is to get the total confirmed and tested cases worldwide, and try to figure the overall positive ratio using `confirmed cases / tested cases`

In [54]:
# Get the total confirmed cases worldwide
total_confirmed<-sum(covid_data_frame_csv$confirmed)
total_confirmed
# Get the total tested cases worldwide
total_tested<-sum(covid_data_frame_csv$tested)
total_tested
# Get the positive ratio (confirmed / tested)
positive_ratio<-total_confirmed/total_tested
positive_ratio

[1] 431434555

[1] 5396881644

[1] 0.07994145

## TASK 6: Get a country list which reported their testing data 

The goal of task 6 is to get a catalog or sorted list of countries who have reported their COVID-19 testing data

In [55]:
# Get the `country` column
countries <- covid_data_frame_csv$country

# Check its class (should be character or factor)
class(countries)

# If it's a factor, convert to character for sorting
if(is.factor(countries)) {
  countries <- as.character(countries)
  cat("Converted from factor to character\n")
}

# Sort the countries A to Z
countries_AtoZ <- sort(countries)

# Sort the countries Z to A
countries_ZtoA <- sort(countries, decreasing = TRUE)

# Print the sorted Z to A list
print(countries_ZtoA)

[1] "character"

  [1] "Zimbabwe"               "Zambia"                 "Vietnam"
  [4] "Venezuela"              "Uzbekistan"             "Uruguay"
  [7] "United States"          "United Kingdom"         "United Arab Emirates"
 [10] "Ukraine"                "Uganda"                 "Turkey"
 [13] "Tunisia"                "Trinidad and Tobago"    "Togo"
 [16] "Thailand"               "Tanzania"               "Taiwan[m]"
 [19] "Switzerland[l]"         "Sweden"                 "Sudan"
 [22] "Sri Lanka"              "Spain"                  "South Sudan"
 [25] "South Korea"            "South Africa"           "Slovenia"
 [28] "Slovakia"               "Singapore"              "Serbia"
 [31] "Senegal"                "Saudi Arabia"           "San Marino"
 [34] "Saint Vincent"          "Saint Lucia"            "Saint Kitts and Nevis"
 [37] "Rwanda"                 "Russia"                 "Romania"
 [40] "Qatar"                  "Portugal"               "Poland"
 [43] "Philippines"            "Peru"                   "Paraguay"
 [46] "Papua New Guinea"       "Panama"                 "Palestine"
 [49] "Pakistan"               "Oman"                   "Norway"
 [52] "Northern Cyprus[k]"     "North Macedonia"        "North Korea"
 [55] "Nigeria"                "Niger"                  "New Zealand"
 [58] "New Caledonia"          "Netherlands"            "Nepal"
 [61] "Namibia"                "Myanmar"                "Mozambique"
 [64] "Morocco"                "Montenegro"             "Mongolia"
 [67] "Moldova[j]"             "Mexico"                 "Mauritius"
 [70] "Mauritania"             "Malta"                  "Mali"
 [73] "Maldives"               "Malaysia"               "Malawi"
 [76] "Madagascar"             "Luxembourg[i]"          "Lithuania"
 [79] "Libya"                  "Liberia"                "Lesotho"
 [82] "Lebanon"                "Latvia"                 "Laos"
 [85] "Kyrgyzstan"             "Kuwait"                 "Kosovo"
 [88] "Kenya"                  "Kazakhstan"             "Jordan"
 [91] "Japan"                  "Jamaica"                "Ivory Coast"
 [94] "Italy"                  "Israel"                 "Ireland"
 [97] "Iraq"                   "Iran"                   "Indonesia"
[100] "India"                  "Iceland"                "Hungary"
[103] "Honduras"               "Haiti"                  "Guyana"
[106] "Guinea-Bissau"          "Guinea"                 "Guatemala"
[109] "Grenada"                "Greenland"              "Greece"
[112] "Ghana"                  "Germany"                "Georgia[h]"
[115] "Gambia"                 "Gabon"                  "France[f][g]"
[118] "Finland"                "Fiji"                   "Faroe Islands"
[121] "Ethiopia"               "Eswatini"               "Estonia"
[124] "Equatorial Guinea"      "El Salvador"            "Egypt"
[127] "Ecuador"                "DR Congo"               "Dominican Republic"
[130] "Dominica"               "Djibouti"               "Denmark[e]"
[133] "Czechia"                "Cyprus[d]"              "Cuba"
[136] "Croatia"                "Costa Rica"             "Colombia"
[139] "China[c]"               "Chile"                  "Chad"
[142] "Canada"                 "Cameroon"               "Cambodia"
[145] "Burundi"                "Burkina Faso"           "Bulgaria"
[148] "Brunei"                 "Brazil"                 "Botswana"
[151] "Bosnia and Herzegovina" "Bolivia"                "Bhutan"
[154] "Benin"                  "Belize"                 "Belgium"
[157] "Belarus"                "Barbados"               "Bangladesh"
[160] "Bahrain"                "Bahamas"                "Azerbaijan"
[163] "Austria"                "Australia"              "Armenia"
[166] "Argentina"              "Antigua and Barbuda"    "Angola"
[169] "Andorra"                "Algeria"                "Albania"
[172] "Afghanistan"

## TASK 7: Identify countries names with a specific pattern

The goal of task 7 is using a regular expression to find any countires start with `United`

In [56]:
# Use a regular expression `United.+` to find matches
matched_countries <- grep("United.+", covid_data_frame_csv$country, value = TRUE, ignore.case = FALSE)

# Print the matched country names
print(matched_countries)

[1] "United Arab Emirates" "United Kingdom"       "United States"

## TASK 8: Pick two countries you are interested, and then review their testing data

The goal of task 8 is to compare the COVID-19 test data between two countires, you will need to select two rows from the dataframe, and select `country`, `confirmed`, `confirmed-population-ratio` columns

In [57]:
# Select a subset (should be only one row) of data frame based on a selected country name and columns
selected_country <- "United States"
country_subset <- covid_data_frame_csv[covid_data_frame_csv$country == selected_country, ]

# Select specific columns (e.g., country, date, tested, confirmed, positive ratio)
selected_columns <- country_subset[, c("country", "date", "tested", "confirmed", "confirmed.tested.ratio")]

# Print the result
print(selected_columns)

          country        date    tested confirmed confirmed.tested.ratio
166 United States 29 Jul 2022 929349291  90749469                    9.8

## TASK 9: Compare which one of the selected countries has a larger ratio of confirmed cases to population

The goal of task 9 is to find out which country you have selected before has larger ratio of confirmed cases to population, which may indicate that country has higher COVID-19 infection risk

In [58]:
country1 <- "United States"
country2 <- "India"

# Get the confirmed.population values
value1 <- covid_data_frame_csv$confirmed.population.ratio[covid_data_frame_csv$country == country1]
value2 <- covid_data_frame_csv$confirmed.population.ratio[covid_data_frame_csv$country == country2]

# If-else statement
if (value1 > value2) {
  print(paste(country1, "has a higher confirmed population ratio (", round(value1, 2), "%) than", 
              country2, "(", round(value2, 2), "%)", sep = ""))
} else if (value2 > value1) {
  print(paste(country2, "has a higher confirmed population ratio (", round(value2, 2), "%) than", 
              country1, "(", round(value1, 2), "%)", sep = ""))
} else {
  print(paste(country1, "and", country2, "have the same confirmed population ratio:", round(value1, 2), "%"))
}

[1] "Indiahas a higher confirmed population ratio (31.7%) thanUnited States(27.4%)"

## TASK 10: Find countries with confirmed to population ratio rate less than a threshold

The goal of task 10 is to find out which countries have the confirmed to population ratio less than 1%, it may indicate the risk of those countries are relatively low

In [59]:
# Set a threshold value (e.g., 1%)
threshold <- 1

# Get subset of countries with confirmed.population.ratio less than the threshold
low_ratio_countries <- covid_data_frame_csv[covid_data_frame_csv$confirmed.population.ratio < threshold, ]

# Display the results
cat("Countries with confirmed.population.ratio less than", threshold, "%:\n")
print(low_ratio_countries[, c("country", "confirmed.population.ratio")])

# Show count
cat("\nNumber of countries:", nrow(low_ratio_countries))

Countries with confirmed.population.ratio less than 1 %:
                country confirmed.population.ratio
1           Afghanistan                    0.13000
3               Algeria                    0.13000
5                Angola                    0.06700
6   Antigua and Barbuda                    0.86000
14           Bangladesh                    0.70000
19                Benin                    0.06700
25               Brunei                    0.07400
27         Burkina Faso                    0.05800
28              Burundi                    0.00740
29             Cambodia                    0.48000
30             Cameroon                    0.12000
32                 Chad                    0.02900
34             China[c]                    0.00610
45             DR Congo                    0.02900
47                Egypt                    0.28000
52             Ethiopia                    0.24000
57                Gabon                    0.08200
58               Gambia                    0.21000
61                Ghana                    0.31000
64              Grenada                    0.14000
66               Guinea                    0.19000
67        Guinea-Bissau                    0.45000
69                Haiti                    0.30000
80          Ivory Coast                    0.13000
82                Japan                    0.34000
85                Kenya                    0.23000
89                 Laos                    0.00063
93              Liberia                    0.11000
97           Madagascar                    0.07600
98               Malawi                    0.46000
101                Mali                    0.07100
103          Mauritania                    0.41000
104           Mauritius                    0.03900
110          Mozambique                    0.34000
111             Myanmar                    0.81000
115       New Caledonia                    0.05000
117               Niger                    0.02100
118             Nigeria                    0.07600
119         North Korea                    0.00000
124            Pakistan                    0.27000
127    Papua New Guinea                    0.01100
136              Rwanda                    0.76000
142             Senegal                    0.29000
148         South Korea                    0.17000
149         South Sudan                    0.08400
151           Sri Lanka                    0.43000
152               Sudan                    0.05300
156            Tanzania                    0.00085
157            Thailand                    0.03800
158                Togo                    0.46000
162              Uganda                    0.08700
168          Uzbekistan                    0.13000
169           Venezuela                    0.55000

Number of countries: 53